-- PRODUCT-PLAN Phase A — financial foundation:
-- balances (dual investing/withdrawable), fee_tiers (9-tier schedule), property yield rate.
CREATE TABLE IF NOT EXISTS "balances" (
  "user_id" text NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "investing_usd" bigint NOT NULL DEFAULT 0,
  "withdrawable_usd" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "balances_pkey" PRIMARY KEY ("user_id"),
  CONSTRAINT "balances_nonneg_check" CHECK ("investing_usd" >= 0 AND "withdrawable_usd" >= 0)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fee_tiers" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "min_amount_usd" bigint NOT NULL,
  "max_amount_usd" bigint,
  "buy_primary_bps" integer NOT NULL,
  "buy_secondary_bps" integer NOT NULL,
  "sell_secondary_bps" integer NOT NULL,
  CONSTRAINT "fee_tiers_min_nonneg_check" CHECK ("min_amount_usd" >= 0),
  CONSTRAINT "fee_tiers_max_gt_min_check" CHECK ("max_amount_usd" IS NULL OR "max_amount_usd" > "min_amount_usd"),
  CONSTRAINT "fee_tiers_bps_range_check" CHECK (
    "buy_primary_bps" BETWEEN 0 AND 10000
    AND "buy_secondary_bps" BETWEEN 0 AND 10000
    AND "sell_secondary_bps" BETWEEN 0 AND 10000
  )
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "fee_tiers_min_uidx" ON "fee_tiers" ("min_amount_usd");
--> statement-breakpoint
-- Fee schedule per PRODUCT-PLAN.md §0.5. Amounts in integer cents; rates in basis points.
-- Idempotent: refresh the seeded schedule; admin edits (if any) are not expected pre-launch.
DELETE FROM "fee_tiers";
--> statement-breakpoint
INSERT INTO "fee_tiers" ("min_amount_usd", "max_amount_usd", "buy_primary_bps", "buy_secondary_bps", "sell_secondary_bps") VALUES
  (8000, 50000, 300, 90, 90),
  (50000, 200000, 250, 80, 80),
  (200000, 1000000, 200, 70, 70),
  (1000000, 5000000, 150, 60, 60),
  (5000000, 20000000, 100, 50, 50),
  (20000000, 50000000, 80, 40, 40),
  (50000000, 100000000, 60, 30, 30),
  (100000000, 999999999, 40, 20, 20),
  (1000000000, NULL, 1, 10, 10);
--> statement-breakpoint
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "monthly_yield_rate" numeric(4,2) NOT NULL DEFAULT '5.50';
--> statement-breakpoint
ALTER TABLE "properties" DROP CONSTRAINT IF EXISTS "properties_yield_range_check";
--> statement-breakpoint
ALTER TABLE "properties" ADD CONSTRAINT "properties_yield_range_check" CHECK ("monthly_yield_rate" >= 4.5 AND "monthly_yield_rate" <= 7.5);
