#!/usr/bin/env python3
"""Phase 8 localization sweep, batch C: LockSheet / SellSheet / LimitBuySheet
money-flow sheet keys. Mirrors all 12 locales."""
import json
import collections
import io

LOCALES = ["en", "ar", "de", "es", "fa", "fr", "hi", "id", "pt", "ru", "tr", "zh"]

K = {
    # ── LockSheet ──
    "lockSheetTitle": {"en": "Lock shares", "ar": "إقفال الأسهم", "de": "Anteile sperren", "es": "Bloquear acciones", "fa": "قفل سهام", "fr": "Verrouiller des actions", "hi": "शेयर लॉक करें", "id": "Kunci saham", "pt": "Bloquear ações", "ru": "Заблокировать акции", "tr": "Hisseleri kilitle", "zh": "锁定股份"},
    "lockSheetIntro": {"en": "Locked shares start earning yield from day 1. Choose how often you get paid.", "ar": "الأسهم المقفلة تكسب عائدًا من اليوم الأول. اختر عدد مرات الدفع.", "de": "Gesperrte Anteile erwirtschaften ab Tag 1 Ertrag. Wähle, wie oft du ausgezahlt wirst.", "es": "Las acciones bloqueadas generan rendimiento desde el día 1. Elige la frecuencia de pago.", "fa": "سهام قفل‌شده از روز اول بازده می‌گیرند. انتخاب کنید چند وقت یک‌بار پرداخت می‌شوید.", "fr": "Les actions verrouillées rapportent dès le 1er jour. Choisissez la fréquence de versement.", "hi": "लॉक शेयर पहले दिन से उपज देने लगते हैं। भुगतान की आवृत्ति चुनें।", "id": "Saham terkunci menghasilkan imbal hasil sejak hari ke-1. Pilih frekuensi pembayaran.", "pt": "Ações bloqueadas rendem desde o dia 1. Escolha a frequência de pagamento.", "ru": "Заблокированные акции приносят доход с 1-го дня. Выберите периодичность выплат.", "tr": "Kilitli hisseler 1. günden itibaren getiri sağlar. Ödeme sıklığını seçin.", "zh": "锁定的股份从第 1 天开始产生收益。选择收款频率。"},
    "payoutPeriodMonthly": {"en": "Monthly", "ar": "شهري", "de": "Monatlich", "es": "Mensual", "fa": "ماهانه", "fr": "Mensuel", "hi": "मासिक", "id": "Bulanan", "pt": "Mensal", "ru": "Ежемесячно", "tr": "Aylık", "zh": "每月"},
    "payoutPeriodWeekly": {"en": "Weekly", "ar": "أسبوعي", "de": "Wöchentlich", "es": "Semanal", "fa": "هفتگی", "fr": "Hebdomadaire", "hi": "साप्ताहिक", "id": "Mingguan", "pt": "Semanal", "ru": "Еженедельно", "tr": "Haftalık", "zh": "每周"},
    "payoutPeriodMonthlyHint": {"en": "full rate, 1 payout / month", "ar": "المعدل الكامل، دفعة واحدة / شهر", "de": "voller Satz, 1 Auszahlung / Monat", "es": "tasa completa, 1 pago / mes", "fa": "نرخ کامل، ۱ پرداخت در ماه", "fr": "taux plein, 1 versement / mois", "hi": "पूरी दर, 1 भुगतान / माह", "id": "tarif penuh, 1 pembayaran / bulan", "pt": "taxa cheia, 1 pagamento / mês", "ru": "полная ставка, 1 выплата / месяц", "tr": "tam oran, ayda 1 ödeme", "zh": "全额利率，每月 1 次派息"},
    "payoutPeriodWeeklyHint": {"en": "rate − 1%, 4 payouts / month", "ar": "المعدل − 1%، 4 دفعات / شهر", "de": "Satz − 1 %, 4 Auszahlungen / Monat", "es": "tasa − 1 %, 4 pagos / mes", "fa": "نرخ منهای ۱٪، ۴ پرداخت در ماه", "fr": "taux − 1 %, 4 versements / mois", "hi": "दर − 1%, 4 भुगतान / माह", "id": "tarif − 1%, 4 pembayaran / bulan", "pt": "taxa − 1%, 4 pagamentos / mês", "ru": "ставка − 1%, 4 выплаты / месяц", "tr": "oran − %1, ayda 4 ödeme", "zh": "利率 − 1%，每月 4 次派息"},
    "payoutPeriodAria": {"en": "Payout {period}", "ar": "دورة {period}", "de": "Auszahlung {period}", "es": "Pago {period}", "fa": "دوره {period}", "fr": "Versement {period}", "hi": "भुगतान {period}", "id": "Pembayaran {period}", "pt": "Pagamento {period}", "ru": "Выплата {period}", "tr": "{period} ödeme", "zh": "{period}派息"},
    "monthlyRate": {"en": "Monthly rate", "ar": "المعدل الشهري", "de": "Monatssatz", "es": "Tasa mensual", "fa": "نرخ ماهانه", "fr": "Taux mensuel", "hi": "मासिक दर", "id": "Tarif bulanan", "pt": "Taxa mensal", "ru": "Месячная ставка", "tr": "Aylık oran", "zh": "月利率"},
    "maxCta": {"en": "Max", "ar": "الحد الأقصى", "de": "Max", "es": "Máx.", "fa": "حداکثر", "fr": "Max", "hi": "अधिकतम", "id": "Maks", "pt": "Máx.", "ru": "Макс.", "tr": "Maks.", "zh": "最大"},
    "quantityInvalid": {"en": "Quantity must be between 1 and {max}.", "ar": "يجب أن تكون الكمية بين 1 و {max}.", "de": "Die Menge muss zwischen 1 und {max} liegen.", "es": "La cantidad debe estar entre 1 y {max}.", "fa": "تعداد باید بین ۱ و {max} باشد.", "fr": "La quantité doit être comprise entre 1 et {max}.", "hi": "मात्रा 1 और {max} के बीच होनी चाहिए।", "id": "Jumlah harus antara 1 dan {max}.", "pt": "A quantidade deve estar entre 1 e {max}.", "ru": "Количество должно быть от 1 до {max}.", "tr": "Miktar 1 ile {max} arasında olmalıdır.", "zh": "数量必须在 1 到 {max} 之间。"},
    "lockedPrincipal": {"en": "Locked principal", "ar": "أصل المبلغ المقفل", "de": "Gesperrtes Kapital", "es": "Principal bloqueado", "fa": "اصل مبلغ قفل‌شده", "fr": "Capital verrouillé", "hi": "लॉक मूलधन", "id": "Pokok terkunci", "pt": "Principal bloqueado", "ru": "Заблокированный капитал", "tr": "Kilitli anapara", "zh": "锁定本金"},
    "monthlyPayout": {"en": "Monthly payout", "ar": "الدفعة الشهرية", "de": "Monatliche Auszahlung", "es": "Pago mensual", "fa": "پرداخت ماهانه", "fr": "Versement mensuel", "hi": "मासिक भुगतान", "id": "Pembayaran bulanan", "pt": "Pagamento mensal", "ru": "Ежемесячная выплата", "tr": "Aylık ödeme", "zh": "月派息"},
    "weeklyPayout": {"en": "Weekly payout", "ar": "الدفعة الأسبوعية", "de": "Wöchentliche Auszahlung", "es": "Pago semanal", "fa": "پرداخت هفتگی", "fr": "Versement hebdomadaire", "hi": "साप्ताहिक भुगतान", "id": "Pembayaran mingguan", "pt": "Pagamento semanal", "ru": "Еженедельная выплата", "tr": "Haftalık ödeme", "zh": "周派息"},
    "perMonthWord": {"en": "/ month", "ar": "/ شهر", "de": "/ Monat", "es": "/ mes", "fa": "/ ماه", "fr": "/ mois", "hi": "/ माह", "id": "/ bulan", "pt": "/ mês", "ru": "/ месяц", "tr": "/ ay", "zh": "/ 月"},
    "perWeekWord": {"en": "/ week", "ar": "/ أسبوع", "de": "/ Woche", "es": "/ semana", "fa": "/ هفته", "fr": "/ semaine", "hi": "/ सप्ताह", "id": "/ minggu", "pt": "/ semana", "ru": "/ неделя", "tr": "/ hafta", "zh": "/ 周"},
    "timesFourMonth": {"en": "× 4 / month", "ar": "× 4 / شهر", "de": "× 4 / Monat", "es": "× 4 / mes", "fa": "× ۴ / ماه", "fr": "× 4 / mois", "hi": "× 4 / माह", "id": "× 4 / bulan", "pt": "× 4 / mês", "ru": "× 4 / месяц", "tr": "× 4 / ay", "zh": "× 4 / 月"},
    "lockConfirmCta": {"en": "Lock {count} {unit} & earn", "ar": "اقفل {count} {unit} واكسب", "de": "{count} {unit} sperren & verdienen", "es": "Bloquear {count} {unit} y ganar", "fa": "{count} {unit} را قفل کن و درآمد بگیر", "fr": "Verrouiller {count} {unit} et gagner", "hi": "{count} {unit} लॉक करें और कमाएँ", "id": "Kunci {count} {unit} & hasilkan", "pt": "Bloquear {count} {unit} e ganhar", "ru": "Заблокировать {count} {unit} и зарабатывать", "tr": "{count} {unit} kilitle ve kazan", "zh": "锁定 {count} {unit} 并开始收益"},
    "lockingPending": {"en": "Locking…", "ar": "جارٍ الإقفال…", "de": "Wird gesperrt…", "es": "Bloqueando…", "fa": "در حال قفل کردن…", "fr": "Verrouillage…", "hi": "लॉक हो रहा है…", "id": "Mengunci…", "pt": "Bloqueando…", "ru": "Блокировка…", "tr": "Kilitleniyor…", "zh": "锁定中…"},
    "lockWarningNote": {"en": "Locked shares can't be sold. Unlock takes 2–3 days and stops yield.", "ar": "لا يمكن بيع الأسهم المقفلة. يستغرق فتح الإقفال 2–3 أيام ويوقف العائد.", "de": "Gesperrte Anteile können nicht verkauft werden. Entsperren dauert 2–3 Tage und stoppt den Ertrag.", "es": "Las acciones bloqueadas no se pueden vender. Desbloquear tarda 2–3 días y detiene el rendimiento.", "fa": "سهام قفل‌شده قابل فروش نیستند. باز کردن قفل ۲ تا ۳ روز طول می‌کشد و بازده را متوقف می‌کند.", "fr": "Les actions verrouillées ne peuvent pas être vendues. Le déverrouillage prend 2 à 3 jours et stoppe le rendement.", "hi": "लॉक शेयर नहीं बेचे जा सकते। अनलॉक में 2–3 दिन लगते हैं और उपज रुक जाती है।", "id": "Saham terkunci tidak dapat dijual. Membuka kunci memakan 2–3 hari dan menghentikan imbal hasil.", "pt": "Ações bloqueadas não podem ser vendidas. Desbloquear leva 2–3 dias e interrompe o rendimento.", "ru": "Заблокированные акции продать нельзя. Разблокировка занимает 2–3 дня и останавливает доходность.", "tr": "Kilitli hisseler satılamaz. Kilit açma 2–3 gün sürer ve getiriyi durdurur.", "zh": "锁定的股份无法卖出。解锁需 2–3 天并会停止收益。"},
    "lockedSuccessTitle": {"en": "Shares locked", "ar": "تم إقفال الأسهم", "de": "Anteile gesperrt", "es": "Acciones bloqueadas", "fa": "سهام قفل شد", "fr": "Actions verrouillées", "hi": "शेयर लॉक हो गए", "id": "Saham terkunci", "pt": "Ações bloqueadas", "ru": "Акции заблокированы", "tr": "Hisseler kilitlendi", "zh": "股份已锁定"},
    "earningFromDay1": {"en": "{count} {unit} earning from day 1", "ar": "{count} {unit} تكسب من اليوم الأول", "de": "{count} {unit} verdienen ab Tag 1", "es": "{count} {unit} generan desde el día 1", "fa": "{count} {unit} از روز اول درآمد دارد", "fr": "{count} {unit} rapportent dès le jour 1", "hi": "{count} {unit} पहले दिन से कमा रहे हैं", "id": "{count} {unit} menghasilkan sejak hari ke-1", "pt": "{count} {unit} rendendo desde o dia 1", "ru": "{count} {unit} приносят доход с 1-го дня", "tr": "{count} {unit} 1. günden kazanıyor", "zh": "{count} {unit} 从第 1 天开始收益"},
    # ── SellSheet ──
    "sellSheetTitle": {"en": "Sell shares", "ar": "بيع الأسهم", "de": "Anteile verkaufen", "es": "Vender acciones", "fa": "فروش سهام", "fr": "Vendre des actions", "hi": "शेयर बेचें", "id": "Jual saham", "pt": "Vender ações", "ru": "Продать акции", "tr": "Hisse sat", "zh": "卖出股份"},
    "confirmInstantSale": {"en": "Confirm instant sale", "ar": "تأكيد البيع الفوري", "de": "Sofortverkauf bestätigen", "es": "Confirmar venta instantánea", "fa": "تأیید فروش فوری", "fr": "Confirmer la vente instantanée", "hi": "तुरंत बिक्री की पुष्टि करें", "id": "Konfirmasi jual instan", "pt": "Confirmar venda instantânea", "ru": "Подтвердить мгновенную продажу", "tr": "Anında satışı onayla", "zh": "确认即时卖出"},
    "sellModeAria": {"en": "Sell mode", "ar": "وضع البيع", "de": "Verkaufsmodus", "es": "Modo de venta", "fa": "حالت فروش", "fr": "Mode de vente", "hi": "बिक्री मोड", "id": "Mode jual", "pt": "Modo de venda", "ru": "Режим продажи", "tr": "Satış modu", "zh": "卖出模式"},
    "sellModeAriaOf": {"en": "Sell {mode}", "ar": "بيع {mode}", "de": "{mode} verkaufen", "es": "Vender {mode}", "fa": "فروش {mode}", "fr": "Vendre {mode}", "hi": "{mode} बेचें", "id": "Jual {mode}", "pt": "Vender {mode}", "ru": "Продать {mode}", "tr": "{mode} sat", "zh": "{mode}卖出"},
    "instantMode": {"en": "Instant", "ar": "فوري", "de": "Sofort", "es": "Instantánea", "fa": "فوری", "fr": "Instantané", "hi": "तुरंत", "id": "Instan", "pt": "Instantânea", "ru": "Мгновенно", "tr": "Anında", "zh": "即时"},
    "customPriceMode": {"en": "Custom price", "ar": "سعر مخصص", "de": "Eigener Preis", "es": "Precio personalizado", "fa": "قیمت دلخواه", "fr": "Prix personnalisé", "hi": "कस्टम कीमत", "id": "Harga kustom", "pt": "Preço personalizado", "ru": "Своя цена", "tr": "Özel fiyat", "zh": "自定义价格"},
    "instantSellReview": {"en": "Review sale · {amount}", "ar": "مراجعة البيع · {amount}", "de": "Verkauf prüfen · {amount}", "es": "Revisar venta · {amount}", "fa": "بازبینی فروش · {amount}", "fr": "Vérifier la vente · {amount}", "hi": "बिक्री की समीक्षा · {amount}", "id": "Tinjau penjualan · {amount}", "pt": "Revisar venda · {amount}", "ru": "Проверить продажу · {amount}", "tr": "Satışı gözden geçir · {amount}", "zh": "确认卖出 · {amount}"},
    "instantSellReviewBody": {"en": "The platform buys back these shares at list price − 7%. This can't be undone.", "ar": "تشتري المنصة هذه الأسهم بسعر القائمة − 7%. لا يمكن التراجع عن هذا.", "de": "Die Plattform kauft diese Anteile zum Listenpreis − 7 % zurück. Dies kann nicht rückgängig gemacht werden.", "es": "La plataforma recompra estas acciones al precio de lista − 7 %. No se puede deshacer.", "fa": "پلتفرم این سهام را با قیمت لیست منهای ۷٪ بازمی‌خرد. این عمل قابل بازگشت نیست.", "fr": "La plateforme rachète ces actions au prix catalogue − 7 %. Irréversible.", "hi": "प्लेटफ़ॉर्म इन शेयरों को सूची मूल्य − 7% पर खरीदता है। इसे पूर्ववत नहीं किया जा सकता।", "id": "Platform membeli kembali saham ini pada harga daftar − 7%. Tidak dapat dibatalkan.", "pt": "A plataforma recompra estas ações ao preço de tabela − 7%. Não pode ser desfeito.", "ru": "Платформа выкупает эти акции по цене каталога − 7%. Отменить нельзя.", "tr": "Platform bu hisseleri liste fiyatı − %7'den geri alır. Bu işlem geri alınamaz.", "zh": "平台按目录价 − 7% 回购这些股份。此操作不可撤销。"},
    "feeLabel": {"en": "Fee (7%)", "ar": "الرسوم (7%)", "de": "Gebühr (7 %)", "es": "Comisión (7 %)", "fa": "کارمزد (۷٪)", "fr": "Frais (7 %)", "hi": "शुल्क (7%)", "id": "Biaya (7%)", "pt": "Taxa (7%)", "ru": "Комиссия (7%)", "tr": "Ücret (%7)", "zh": "费用 (7%)"},
    "youReceive": {"en": "You receive", "ar": "تستلم", "de": "Du erhältst", "es": "Recibes", "fa": "شما دریافت می‌کنید", "fr": "Vous recevez", "hi": "आपको मिलेगा", "id": "Anda menerima", "pt": "Você recebe", "ru": "Вы получите", "tr": "Alacağınız", "zh": "您将收到"},
    "confirmSell": {"en": "Confirm sell", "ar": "تأكيد البيع", "de": "Verkauf bestätigen", "es": "Confirmar venta", "fa": "تأیید فروش", "fr": "Confirmer la vente", "hi": "बिक्री की पुष्टि करें", "id": "Konfirmasi jual", "pt": "Confirmar venda", "ru": "Подтвердить продажу", "tr": "Satışı onayla", "zh": "确认卖出"},
    "sellingPending": {"en": "Selling…", "ar": "جارٍ البيع…", "de": "Wird verkauft…", "es": "Vendiendo…", "fa": "در حال فروش…", "fr": "Vente en cours…", "hi": "बिक रहा है…", "id": "Menjual…", "pt": "Vendendo…", "ru": "Продаётся…", "tr": "Satılıyor…", "zh": "卖出中…"},
    "placingPending": {"en": "Placing…", "ar": "جارٍ الإرسال…", "de": "Wird platziert…", "es": "Enviando…", "fa": "در حال ثبت…", "fr": "Envoi en cours…", "hi": "दर्ज हो रहा है…", "id": "Menempatkan…", "pt": "A colocar…", "ru": "Размещение…", "tr": "Veriliyor…", "zh": "提交中…"},
    "lockedInOrders": {"en": "Locked / in orders", "ar": "مقفل / في الأوامر", "de": "Gesperrt / in Orders", "es": "Bloqueadas / en órdenes", "fa": "قفل‌شده / در سفارش‌ها", "fr": "Verrouillées / en cours", "hi": "लॉक / ऑर्डर में", "id": "Terkunci / dalam order", "pt": "Bloqueadas / em ordens", "ru": "Заблокировано / в заявках", "tr": "Kilitli / emirde", "zh": "已锁定 / 挂单中"},
    "notSellable": {"en": "not sellable", "ar": "غير قابلة للبيع", "de": "nicht verkäuflich", "es": "no vendible", "fa": "قابل فروش نیست", "fr": "non vendable", "hi": "बिकने योग्य नहीं", "id": "tidak dapat dijual", "pt": "não vendável", "ru": "не продаётся", "tr": "satılamaz", "zh": "不可卖出"},
    "onTrade": {"en": "on trade", "ar": "على التداول", "de": "beim Handel", "es": "por operación", "fa": "روی معامله", "fr": "sur transaction", "hi": "ट्रेड पर", "id": "per transaksi", "pt": "por negócio", "ru": "со сделки", "tr": "işlem başına", "zh": "按成交"},
    "instantSellEnded": {"en": "Instant sell ended — the primary offering is sold out. Use a custom price.", "ar": "انتهى البيع الفوري — نفدت الطروحة الأساسية. استخدم سعرًا مخصصًا.", "de": "Sofortverkauf beendet — das Primärangebot ist ausverkauft. Nutze einen eigenen Preis.", "es": "La venta instantánea terminó: la oferta primaria está agotada. Usa un precio personalizado.", "fa": "فروش فوری پایان یافت — عرضه اولیه به پایان رسیده است. از قیمت دلخواه استفاده کنید.", "fr": "Vente instantanée terminée — l'offre primaire est épuisée. Utilisez un prix personnalisé.", "hi": "तुरंत बिक्री समाप्त — प्राथमिक ऑफर बिक चुका। कस्टम कीमत का उपयोग करें।", "id": "Jual instan berakhir — penawaran primer habis. Gunakan harga kustom.", "pt": "Venda instantânea encerrada — a oferta primária esgotou. Use um preço personalizado.", "ru": "Мгновенная продажа завершена — первичное предложение распродано. Укажите свою цену.", "tr": "Anında satış sona erdi — birincil arz tükendi. Özel bir fiyat kullanın.", "zh": "即时卖出已结束——一手发售已售罄。请使用自定义价格。"},
    "queueSellOrder": {"en": "Queue sell order", "ar": "جدولة أمر البيع", "de": "Verkaufsorder in Warteschlange", "es": "En cola de venta", "fa": "قرار دادن سفارش فروش در صف", "fr": "Mettre l'ordre de vente en file", "hi": "सेल ऑर्डर कतार में डालें", "id": "Antrekan order jual", "pt": "Colocar ordem de venda na fila", "ru": "Поставить заявку на продажу в очередь", "tr": "Satış emrini kuyruğa al", "zh": "排队卖出订单"},
    "placeSellOrder": {"en": "Place sell order", "ar": "إرسال أمر البيع", "de": "Verkaufsorder aufgeben", "es": "Colocar orden de venta", "fa": "ثبت سفارش فروش", "fr": "Passer l'ordre de vente", "hi": "सेल ऑर्डर दर्ज करें", "id": "Tempatkan order jual", "pt": "Colocar ordem de venda", "ru": "Разместить заявку на продажу", "tr": "Satış emri ver", "zh": "提交卖出订单"},
    "queuedUntilSellout": {"en": "Queued until the primary offering sells out — then your order goes live on the market automatically.", "ar": "يُجدول حتى نفاد الطروحة الأساسية — ثم يُفعَّل أمرك في السوق تلقائيًا.", "de": "In der Warteschlange, bis das Primärangebot ausverkauft ist — dann geht deine Order automatisch an den Markt.", "es": "En cola hasta que se agote la oferta primaria; luego tu orden saldrá al mercado automáticamente.", "fa": "در صف می‌ماند تا عرضه اولیه به پایان برسد — سپس سفارش شما به‌طور خودکار در بازار فعال می‌شود.", "fr": "En file jusqu'à l'épuisement de l'offre primaire — votre ordre passera ensuite automatiquement sur le marché.", "hi": "प्राथमिक ऑफर बिकने तक कतार में — फिर आपका ऑर्डर अपने आप बाज़ार में चालू हो जाएगा।", "id": "Di antrekan sampai penawaran primer habis — lalu order Anda aktif di pasar secara otomatis.", "pt": "Na fila até a oferta primária esgotar — depois sua ordem vai ao mercado automaticamente.", "ru": "В очереди до распродажи первичного предложения — затем заявка автоматически выйдет на рынок.", "tr": "Birincil arz tükenene kadar kuyrukta — sonra emriniz otomatik olarak piyasada işlem görür.", "zh": "排队至一手发售售罄——届时您的订单将自动进入市场。"},
    "platformBuybackNote": {"en": "Platform buys back at list price − 7%. Credited to your investing balance.", "ar": "تشتري المنصة بسعر القائمة − 7%. يُضاف إلى رصيد الاستثمار.", "de": "Plattform kauft zum Listenpreis − 7 % zurück. Gutschrift auf dein Anlageguthaben.", "es": "La plataforma recompra al precio de lista − 7 %. Acreditado a tu saldo de inversión.", "fa": "پلتفرم با قیمت لیست منهای ۷٪ بازمی‌خرد. به موجودی سرمایه‌گذاری شما واریز می‌شود.", "fr": "La plateforme rachète au prix catalogue − 7 %. Crédité sur votre solde d'investissement.", "hi": "प्लेटफ़ॉर्म सूची मूल्य − 7% पर खरीदता है। आपके निवेश बैलेंस में जोड़ा जाएगा।", "id": "Platform membeli kembali pada harga daftar − 7%. Masuk ke saldo investasi Anda.", "pt": "A plataforma recompra ao preço de tabela − 7%. Creditado no seu saldo de investimento.", "ru": "Платформа выкупает по цене каталога − 7%. Зачисляется на инвестиционный баланс.", "tr": "Platform liste fiyatı − %7'den geri alır. Yatırım bakiyenize yatırılır.", "zh": "平台按目录价 − 7% 回购。款项计入您的投资余额。"},
    "sellSuccessTitle": {"en": "Shares sold", "ar": "تم بيع الأسهم", "de": "Anteile verkauft", "es": "Acciones vendidas", "fa": "سهام فروخته شد", "fr": "Actions vendues", "hi": "शेयर बिक गए", "id": "Saham terjual", "pt": "Ações vendidas", "ru": "Акции проданы", "tr": "Hisseler satıldı", "zh": "股份已卖出"},
    "creditedNote": {"en": "Credited to your investing balance.", "ar": "يُضاف إلى رصيد الاستثمار.", "de": "Gutschrift auf dein Anlageguthaben.", "es": "Acreditado a tu saldo de inversión.", "fa": "به موجودی سرمایه‌گذاری شما واریز می‌شود.", "fr": "Crédité sur votre solde d'investissement.", "hi": "आपके निवेश बैलेंस में जोड़ा जाएगा।", "id": "Masuk ke saldo investasi Anda.", "pt": "Creditado no seu saldo de investimento.", "ru": "Зачисляется на инвестиционный баланс.", "tr": "Yatırım bakiyenize yatırılır.", "zh": "款项计入您的投资余额。"},
    "backCta": {"en": "Back", "ar": "رجوع", "de": "Zurück", "es": "Atrás", "fa": "بازگشت", "fr": "Retour", "hi": "वापस", "id": "Kembali", "pt": "Voltar", "ru": "Назад", "tr": "Geri", "zh": "返回"},
    "sellOrderPlacedToast": {"en": "Sell order placed", "ar": "تم إرسال أمر البيع", "de": "Verkaufsorder aufgegeben", "es": "Orden de venta colocada", "fa": "سفارش فروش ثبت شد", "fr": "Ordre de vente passé", "hi": "सेल ऑर्डर दर्ज हो गया", "id": "Order jual ditempatkan", "pt": "Ordem de venda colocada", "ru": "Заявка на продажу размещена", "tr": "Satış emri verildi", "zh": "卖出订单已提交"},
    "sellOrderPlacedBody": {"en": "Track it in Portfolio → Open orders", "ar": "تابعها في المحفظة → الأوامر المفتوحة", "de": "Verfolge sie unter Portfolio → Offene Orders", "es": "Síguela en Cartera → Órdenes abiertas", "fa": "در پرتفوی → سفارش‌های باز دنبال کنید", "fr": "Suivez-la dans Portefeuille → Ordres ouverts", "hi": "पोर्टफोलियो → खुले ऑर्डर में देखें", "id": "Lacak di Portofolio → Order terbuka", "pt": "Acompanhe em Carteira → Ordens abertas", "ru": "Отслеживайте в Портфеле → Открытые заявки", "tr": "Portföy → Açık emirler'den takip edin", "zh": "在「投资组合 → 挂单」中查看"},
    # ── LimitBuySheet ──
    "buyOnMarket": {"en": "Buy on market", "ar": "شراء من السوق", "de": "Am Markt kaufen", "es": "Comprar en el mercado", "fa": "خرید از بازار", "fr": "Acheter sur le marché", "hi": "बाज़ार से खरीदें", "id": "Beli di pasar", "pt": "Comprar no mercado", "ru": "Купить на рынке", "tr": "Piyasadan al", "zh": "从市场买入"},
    "lastPrice": {"en": "Last price", "ar": "آخر سعر", "de": "Letzter Preis", "es": "Último precio", "fa": "آخرین قیمت", "fr": "Dernier prix", "hi": "अंतिम कीमत", "id": "Harga terakhir", "pt": "Último preço", "ru": "Последняя цена", "tr": "Son fiyat", "zh": "最新价格"},
    "marketFeeLabel": {"en": "Market fee", "ar": "رسوم السوق", "de": "Marktgebühr", "es": "Comisión de mercado", "fa": "کارمزد بازار", "fr": "Frais de marché", "hi": "मार्केट शुल्क", "id": "Biaya pasar", "pt": "Taxa de mercado", "ru": "Рыночная комиссия", "tr": "Piyasa ücreti", "zh": "市场费用"},
    "heldInEscrow": {"en": "Held in escrow", "ar": "محتجز كضمان", "de": "In Treuhandschaft", "es": "Retenido en depósito", "fa": "در سپرده امانی", "fr": "Placé sous séquestre", "hi": "एस्क्रो में रखा", "id": "Ditahan di escrow", "pt": "Retido em custódia", "ru": "В депозите (эскроу)", "tr": "Escrow'da tutuluyor", "zh": "托管中"},
    "escrowNote": {"en": "Funds are held from your investing balance until the order fills — or you cancel it.", "ar": "تُحتجز الأموال من رصيد الاستثمار حتى يُنفَّذ الأمر — أو تلغيه.", "de": "Mittel werden von deinem Anlageguthaben einbehalten, bis die Order ausgeführt wird — oder du löschst sie.", "es": "Los fondos se retienen de tu saldo de inversión hasta que la orden se ejecute, o la cancelas.", "fa": "مبلغ از موجودی سرمایه‌گذاری شما نگه داشته می‌شود تا سفارش پر شود — یا آن را لغو کنید.", "fr": "Les fonds sont retenus sur votre solde d'investissement jusqu'à l'exécution de l'ordre — ou son annulation.", "hi": "ऑर्डर पूरा होने तक — या आपके रद्द करने तक — राशि आपके निवेश बैलेंस से रोकी जाती है।", "id": "Dana ditahan dari saldo investasi Anda sampai order terisi — atau Anda membatalkannya.", "pt": "Os fundos ficam retidos do seu saldo de investimento até a ordem ser executada — ou você a cancelar.", "ru": "Средства удерживаются с инвестиционного баланса до исполнения заявки — или её отмены.", "tr": "Bakiyenizden tutar, emir gerçekleşene kadar — ya da iptal edene kadar — bloke edilir.", "zh": "资金将从您的投资余额中扣除并托管，直至订单成交——或您取消订单。"},
    "buyOrderPlacedToast": {"en": "Buy order placed", "ar": "تم إرسال أمر الشراء", "de": "Kauforder aufgegeben", "es": "Orden de compra colocada", "fa": "سفارش خرید ثبت شد", "fr": "Ordre d'achat passé", "hi": "बाय ऑर्डर दर्ज हो गया", "id": "Order beli ditempatkan", "pt": "Ordem de compra colocada", "ru": "Заявка на покупку размещена", "tr": "Alış emri verildi", "zh": "买入订单已提交"},
    "buyOrderPlacedBody": {"en": "Funds held in escrow until it fills", "ar": "تُحتجز الأموال كضمان حتى يُنفَّذ الأمر", "de": "Mittel bleiben im Treuhandkonto, bis die Order ausgeführt wird", "es": "Fondos retenidos en depósito hasta que se ejecute", "fa": "مبلغ تا زمان اجرای سفارش در سپرده امانی می‌ماند", "fr": "Fonds sous séquestre jusqu'à l'exécution", "hi": "ऑर्डर पूरा होने तक राशि एस्क्रो में", "id": "Dana ditahan di escrow sampai terisi", "pt": "Fundos retidos em custódia até a execução", "ru": "Средства в депозите до исполнения заявки", "tr": "Emir gerçekleşene kadar fonlar escrow'da", "zh": "资金托管至订单成交"},
    "placeBuyOrder": {"en": "Place buy order", "ar": "إرسال أمر الشراء", "de": "Kauforder aufgeben", "es": "Colocar orden de compra", "fa": "ثبت سفارش خرید", "fr": "Passer l'ordre d'achat", "hi": "बाय ऑर्डर दर्ज करें", "id": "Tempatkan order beli", "pt": "Colocar ordem de compra", "ru": "Разместить заявку на покупку", "tr": "Alış emri ver", "zh": "提交买入订单"},
}


def main():
    for loc in LOCALES:
        p = f"messages/{loc}.json"
        data = json.load(open(p, encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
        prop = data.setdefault("property", collections.OrderedDict())
        added = 0
        for key, per_locale in K.items():
            if key in prop:
                continue
            prop[key] = per_locale[loc]
            added += 1
        with io.open(p, "w", encoding="utf-8", newline="\n") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"{loc}: +{added}")


if __name__ == "__main__":
    main()
