#!/usr/bin/env python3
"""Phase 8 localization sweep, batch B: lock/sell/buy money-flow keys.
Mirrors all 12 locales."""
import json
import collections
import io

LOCALES = ["en", "ar", "de", "es", "fa", "fr", "hi", "id", "pt", "ru", "tr", "zh"]

K = {
    # ── YieldLockSection ──
    "yieldSection": {"en": "Yield", "ar": "العائد", "de": "Ertrag", "es": "Rendimiento", "fa": "بازده", "fr": "Rendement", "hi": "उपज", "id": "Imbal hasil", "pt": "Rendimento", "ru": "Доходность", "tr": "Getiri", "zh": "收益"},
    "monthlyYield": {"en": "Monthly yield", "ar": "العائد الشهري", "de": "Monatsertrag", "es": "Rendimiento mensual", "fa": "بازده ماهانه", "fr": "Rendement mensuel", "hi": "मासिक उपज", "id": "Imbal hasil bulanan", "pt": "Rendimento mensal", "ru": "Доходность в месяц", "tr": "Aylık getiri", "zh": "月收益"},
    "onLockedSharesNote": {"en": "On locked shares · weekly option pays rate − 1%", "ar": "على الأسهم المقفلة · الخيار الأسبوعي يدفع المعدل − 1%", "de": "Auf gesperrte Anteile · Wochenoption zahlt Satz − 1 %", "es": "Sobre acciones bloqueadas · la opción semanal paga tasa − 1 %", "fa": "روی سهام قفل‌شده · گزینه هفتگی نرخ منهای ۱٪ می‌پردازد", "fr": "Sur actions verrouillées · l'option hebdomadaire paie taux − 1 %", "hi": "लॉक शेयर पर · साप्ताहिक विकल्प दर − 1% का भुगतान करता है", "id": "Pada saham terkunci · opsi mingguan membayar rate − 1%", "pt": "Sobre ações bloqueadas · a opção semanal paga taxa − 1%", "ru": "На заблокированные акции · недельный вариант платит ставку − 1%", "tr": "Kilitli hisselerde · haftalık seçenek oran − %1 öder", "zh": "针对已锁定股份 · 周付选项利率 − 1%"},
    "yourShares": {"en": "Your shares", "ar": "أسهمك", "de": "Deine Anteile", "es": "Tus acciones", "fa": "سهام شما", "fr": "Vos actions", "hi": "आपके शेयर", "id": "Saham Anda", "pt": "Suas ações", "ru": "Ваши акции", "tr": "Hisseleriniz", "zh": "您的股份"},
    "freeToLock": {"en": "Free to lock", "ar": "متاحة للإقفال", "de": "Zum Sperren verfügbar", "es": "Libres para bloquear", "fa": "آزاد برای قفل", "fr": "Disponibles au verrouillage", "hi": "लॉक के लिए उपलब्ध", "id": "Bebas dikunci", "pt": "Livres para bloquear", "ru": "Доступно к блокировке", "tr": "Kilitlenebilir", "zh": "可锁定"},
    "buyFirstNote": {"en": "Buy shares first, then lock them to start earning from day one.", "ar": "اشترِ الأسهم أولًا، ثم اقفلها لتبدأ الكسب من اليوم الأول.", "de": "Kaufe zuerst Anteile und sperre sie, um ab Tag eins zu verdienen.", "es": "Compra acciones primero y bloquéalas para ganar desde el primer día.", "fa": "اول سهام بخرید، سپس آن‌ها را قفل کنید تا از روز اول درآمد داشته باشید.", "fr": "Achetez d'abord des actions, puis verrouillez-les pour gagner dès le premier jour.", "hi": "पहले शेयर खरीदें, फिर उन्हें लॉक करें और पहले दिन से कमाई शुरू करें।", "id": "Beli saham dulu, lalu kunci untuk mulai menghasilkan sejak hari pertama.", "pt": "Compre ações primeiro e bloqueie-as para ganhar desde o primeiro dia.", "ru": "Сначала купите акции, затем заблокируйте их, чтобы зарабатывать с первого дня.", "tr": "Önce hisse satın alın, sonra birinci günden kazanmak için kilitleyin.", "zh": "先购买股份，再锁定它们，从第一天开始收益。"},
    "allLocked": {"en": "All locked", "ar": "الكل مقفل", "de": "Alle gesperrt", "es": "Todo bloqueado", "fa": "همه قفل شده", "fr": "Tout verrouillé", "hi": "सब लॉक हैं", "id": "Semua terkunci", "pt": "Tudo bloqueado", "ru": "Все заблокировано", "tr": "Tümü kilitli", "zh": "已全部锁定"},
    "lockCta": {"en": "Lock", "ar": "إقفال", "de": "Sperren", "es": "Bloquear", "fa": "قفل", "fr": "Verrouiller", "hi": "लॉक", "id": "Kunci", "pt": "Bloquear", "ru": "Заблокировать", "tr": "Kilitle", "zh": "锁定"},
    "requestUnlock": {"en": "Request unlock", "ar": "طلب فتح الإقفال", "de": "Entsperren anfordern", "es": "Solicitar desbloqueo", "fa": "درخواست باز کردن قفل", "fr": "Demander le déverrouillage", "hi": "अनलॉक का अनुरोध करें", "id": "Minta buka kunci", "pt": "Solicitar desbloqueio", "ru": "Запросить разблокировку", "tr": "Kilit açma isteği", "zh": "申请解锁"},
    "requesting": {"en": "Requesting…", "ar": "جارٍ الإرسال…", "de": "Wird angefordert…", "es": "Solicitando…", "fa": "در حال درخواست…", "fr": "Demande en cours…", "hi": "अनुरोध जारी…", "id": "Meminta…", "pt": "Solicitando…", "ru": "Отправка запроса…", "tr": "İstek gönderiliyor…", "zh": "请求中…"},
    "unlockPendingNote": {"en": "Yield stopped at your unlock request. Shares become sellable in 2–3 days.", "ar": "توقف العائد عند طلب فتح الإقفال. تصبح الأسهم قابلة للبيع خلال 2–3 أيام.", "de": "Der Ertrag endete mit deiner Entsperranforderung. Anteile sind in 2–3 Tagen wieder verkäuflich.", "es": "El rendimiento se detuvo al solicitar el desbloqueo. Las acciones se pueden vender en 2–3 días.", "fa": "بازده با درخواست باز کردن قفل متوقف شد. سهام طی ۲ تا ۳ روز قابل فروش می‌شوند.", "fr": "Le rendement s'est arrêté à votre demande de déverrouillage. Les actions revendables dans 2 à 3 jours.", "hi": "अनलॉक अनुरोध पर उपज रुक गई। शेयर 2–3 दिन में बिकने योग्य हो जाएंगे।", "id": "Imbal hasil berhenti saat permintaan buka kunci Anda. Saham dapat dijual dalam 2–3 hari.", "pt": "O rendimento parou no seu pedido de desbloqueio. As ações ficam vendáveis em 2–3 dias.", "ru": "Доходность остановлена по вашему запросу. Акции станут продаваемыми через 2–3 дня.", "tr": "Kilit açma isteğinizle getiri durdu. Hisseler 2–3 gün içinde satılabilir olur.", "zh": "收益已在您申请解锁时停止。股份将在 2–3 天后可卖出。"},
    "nShares": {"en": "{count} shares", "ar": "{count} سهم", "de": "{count} Anteile", "es": "{count} acciones", "fa": "{count} سهم", "fr": "{count} actions", "hi": "{count} शेयर", "id": "{count} saham", "pt": "{count} ações", "ru": "{count} акций", "tr": "{count} hisse", "zh": "{count} 股"},
    "accruingWeekly": {"en": "Accruing · weekly", "ar": "تتراكم · أسبوعي", "de": "Läuft auf · wöchentlich", "es": "Acumulando · semanal", "fa": "در حال تجمع · هفتگی", "fr": "En cumul · hebdomadaire", "hi": "संचय · साप्ताहिक", "id": "Berakumulasi · mingguan", "pt": "Acumulando · semanal", "ru": "Накопление · еженедельно", "tr": "Birikiyor · haftalık", "zh": "累计中 · 每周"},
    "accruingMonthly": {"en": "Accruing · monthly", "ar": "تتراكم · شهري", "de": "Läuft auf · monatlich", "es": "Acumulando · mensual", "fa": "در حال تجمع · ماهانه", "fr": "En cumul · mensuel", "hi": "संचय · मासिक", "id": "Berakumulasi · bulanan", "pt": "Acumulando · mensal", "ru": "Накопление · ежемесячно", "tr": "Birikiyor · aylık", "zh": "累计中 · 每月"},
    "unlocksOn": {"en": "Unlocks {date}", "ar": "يُفتح في {date}", "de": "Entsperrt {date}", "es": "Se desbloquea {date}", "fa": "در {date} باز می‌شود", "fr": "Déverrouillage {date}", "hi": "{date} को अनलॉक", "id": "Buka kunci {date}", "pt": "Desbloqueia {date}", "ru": "Разблокировка {date}", "tr": "{date} tarihinde açılır", "zh": "{date} 解锁"},
    "unlockingInDays": {"en": "2–3 days", "ar": "2–3 أيام", "de": "2–3 Tage", "es": "2–3 días", "fa": "۲ تا ۳ روز", "fr": "2 à 3 jours", "hi": "2–3 दिन", "id": "2–3 hari", "pt": "2–3 dias", "ru": "2–3 дня", "tr": "2–3 gün", "zh": "2–3 天"},
    "perWeek": {"en": "Per week", "ar": "أسبوعيًا", "de": "Pro Woche", "es": "Por semana", "fa": "هر هفته", "fr": "Par semaine", "hi": "प्रति सप्ताह", "id": "Per minggu", "pt": "Por semana", "ru": "В неделю", "tr": "Haftada", "zh": "每周"},
    "perMonth": {"en": "Per month", "ar": "شهريًا", "de": "Pro Monat", "es": "Por mes", "fa": "هر ماه", "fr": "Par mois", "hi": "प्रति माह", "id": "Per bulan", "pt": "Por mês", "ru": "В месяц", "tr": "Ayda", "zh": "每月"},
    "unlockConfirmTitle": {"en": "Unlock shares", "ar": "فتح إقفال الأسهم", "de": "Anteile entsperren", "es": "Desbloquear acciones", "fa": "باز کردن قفل سهام", "fr": "Déverrouiller des actions", "hi": "शेयर अनलॉक करें", "id": "Buka kunci saham", "pt": "Desbloquear ações", "ru": "Разблокировать акции", "tr": "Hisselerin kilidini aç", "zh": "解锁股份"},
    "unlockConfirmBody": {"en": "Unlocking stops yield on these shares now. They become sellable in 2–3 days.", "ar": "يوقف فتح الإقفال العائد على هذه الأسهم الآن. تصبح قابلة للبيع خلال 2–3 أيام.", "de": "Das Entsperren stoppt den Ertrag dieser Anteile sofort. Sie sind in 2–3 Tagen wieder verkäuflich.", "es": "Desbloquear detiene el rendimiento de estas acciones ahora. Se pueden vender en 2–3 días.", "fa": "باز کردن قفل، بازده این سهام را همین حالا متوقف می‌کند. طی ۲ تا ۳ روز قابل فروش می‌شوند.", "fr": "Le déverrouillage stoppe le rendement de ces actions. Elles revendables dans 2 à 3 jours.", "hi": "अनलॉक करने से इन शेयरों की उपज अभी रुक जाएगी। ये 2–3 दिन में बिकने योग्य होंगे।", "id": "Membuka kunci menghentikan imbal hasil saham ini sekarang. Dapat dijual dalam 2–3 hari.", "pt": "Desbloquear interrompe o rendimento destas ações agora. Ficam vendáveis em 2–3 dias.", "ru": "Разблокировка сразу останавливает доходность этих акций. Продать их можно будет через 2–3 дня.", "tr": "Kilidi açmak bu hisselerin getirisini şimdi durdurur. 2–3 gün içinde satılabilir hale gelirler.", "zh": "解锁会立即停止这些股份的收益。2–3 天后可卖出。"},
    "unlockConfirmCta": {"en": "Confirm unlock", "ar": "تأكيد فتح الإقفال", "de": "Entsperren bestätigen", "es": "Confirmar desbloqueo", "fa": "تأیید باز کردن قفل", "fr": "Confirmer le déverrouillage", "hi": "अनलॉक की पुष्टि करें", "id": "Konfirmasi buka kunci", "pt": "Confirmar desbloqueio", "ru": "Подтвердить разблокировку", "tr": "Kilit açmayı onayla", "zh": "确认解锁"},
    "unlockPendingLabel": {"en": "Unlocking…", "ar": "جارٍ فتح الإقفال…", "de": "Wird entsperrt…", "es": "Desbloqueando…", "fa": "در حال باز کردن قفل…", "fr": "Déverrouillage…", "hi": "अनलॉक हो रहा है…", "id": "Membuka kunci…", "pt": "Desbloqueando…", "ru": "Разблокировка…", "tr": "Kilit açılıyor…", "zh": "解锁中…"},
    "unlockSuccessTitle": {"en": "Unlock requested", "ar": "تم طلب فتح الإقفال", "de": "Entsperrung angefordert", "es": "Desbloqueo solicitado", "fa": "درخواست باز کردن قفل ثبت شد", "fr": "Déverrouillage demandé", "hi": "अनलॉक का अनुरोध किया", "id": "Permintaan buka kunci dikirim", "pt": "Desbloqueio solicitado", "ru": "Разблокировка запрошена", "tr": "Kilit açma istendi", "zh": "已申请解锁"},
    "unlockSuccessBody": {"en": "Yield has stopped. Shares become sellable in 2–3 days.", "ar": "توقف العائد. تصبح الأسهم قابلة للبيع خلال 2–3 أيام.", "de": "Der Ertrag wurde gestoppt. Anteile sind in 2–3 Tagen wieder verkäuflich.", "es": "El rendimiento se ha detenido. Las acciones se pueden vender en 2–3 días.", "fa": "بازده متوقف شد. سهام طی ۲ تا ۳ روز قابل فروش می‌شوند.", "fr": "Le rendement est stoppé. Les actions revendables dans 2 à 3 jours.", "hi": "उपज रुक गई। शेयर 2–3 दिन में बिकने योग्य होंगे।", "id": "Imbal hasil telah berhenti. Saham dapat dijual dalam 2–3 hari.", "pt": "O rendimento parou. As ações ficam vendáveis em 2–3 dias.", "ru": "Доходность остановлена. Акции можно будет продать через 2–3 дня.", "tr": "Getiri durdu. Hisseler 2–3 gün içinde satılabilir olacak.", "zh": "收益已停止。股份将在 2–3 天后可卖出。"},
    "propertyLabel": {"en": "Property", "ar": "العقار", "de": "Immobilie", "es": "Propiedad", "fa": "ملک", "fr": "Bien", "hi": "संपत्ति", "id": "Properti", "pt": "Imóvel", "ru": "Объект", "tr": "Mülk", "zh": "物业"},
    "sharesLabel": {"en": "Shares", "ar": "الأسهم", "de": "Anteile", "es": "Acciones", "fa": "سهام", "fr": "Actions", "hi": "शेयर", "id": "Saham", "pt": "Ações", "ru": "Акции", "tr": "Hisseler", "zh": "股份"},
    "payoutPeriodLabel": {"en": "Payout period", "ar": "دورة الدفع", "de": "Auszahlungszeitraum", "es": "Período de pago", "fa": "دوره پرداخت", "fr": "Période de versement", "hi": "भुगतान अवधि", "id": "Periode pembayaran", "pt": "Período de pagamento", "ru": "Период выплат", "tr": "Ödeme dönemi", "zh": "派息周期"},
    "weeklyLabel": {"en": "Weekly", "ar": "أسبوعي", "de": "Wöchentlich", "es": "Semanal", "fa": "هفتگی", "fr": "Hebdomadaire", "hi": "साप्ताहिक", "id": "Mingguan", "pt": "Semanal", "ru": "Еженедельно", "tr": "Haftalık", "zh": "每周"},
    "monthlyLabel": {"en": "Monthly", "ar": "شهري", "de": "Monatlich", "es": "Mensual", "fa": "ماهانه", "fr": "Mensuel", "hi": "मासिक", "id": "Bulanan", "pt": "Mensal", "ru": "Ежемесячно", "tr": "Aylık", "zh": "每月"},
    "accruedUnpaidLabel": {"en": "Accrued unpaid", "ar": "المستحق غير المدفوع", "de": "Aufgelaufen, unbezahlt", "es": "Devengado no pagado", "fa": "سرمایه‌نشده پرداخت‌نشده", "fr": "Acquis non versé", "hi": "संचित अवैतनिक", "id": "Terutang belum dibayar", "pt": "Acumulado não pago", "ru": "Начислено, не выплачено", "tr": "Biriken ödenmemiş", "zh": "已计提未付"},
}


def main():
    for loc in LOCALES:
        p = f"messages/{loc}.json"
        data = json.load(open(p, encoding="utf-8"), object_pairs_hook=collections.OrderedDict)
        prop = data.setdefault("property", collections.OrderedDict())
        added = 0
        for key, per_locale in K.items():
            if key in prop:
                continue
            prop[key] = per_locale[loc]
            added += 1
        with io.open(p, "w", encoding="utf-8", newline="\n") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"{loc}: +{added}")


if __name__ == "__main__":
    main()
