#!/usr/bin/env python3
"""Phase 8 localization sweep, batch A: market/orderbook/trades/yield/banner/
about/gallery/trust/similar/hero/sticky/metrics keys. Mirrors all 12 locales."""
import json
import collections
import io

LOCALES = ["en", "ar", "de", "es", "fa", "fr", "hi", "id", "pt", "ru", "tr", "zh"]

K = {
    "marketTitle": {"en": "Market", "ar": "السوق", "de": "Markt", "es": "Mercado", "fa": "بازار", "fr": "Marché", "hi": "बाज़ार", "id": "Pasar", "pt": "Mercado", "ru": "Рынок", "tr": "Pazar", "zh": "市场"},
    "currentPrice": {"en": "Current price", "ar": "السعر الحالي", "de": "Aktueller Preis", "es": "Precio actual", "fa": "قیمت فعلی", "fr": "Prix actuel", "hi": "वर्तमान कीमत", "id": "Harga saat ini", "pt": "Preço atual", "ru": "Текущая цена", "tr": "Güncel fiyat", "zh": "当前价格"},
    "bestBid": {"en": "Best Bid", "ar": "أفضل عرض شراء", "de": "Bestes Gebot", "es": "Mejor compra", "fa": "بهترین خرید", "fr": "Meilleure offre", "hi": "सर्वोत्तम बिड", "id": "Bid terbaik", "pt": "Melhor compra", "ru": "Лучшая ставка", "tr": "En iyi alış", "zh": "最佳买价"},
    "bestAsk": {"en": "Best Ask", "ar": "أفضل عرض بيع", "de": "Bester Ask", "es": "Mejor venta", "fa": "بهترین فروش", "fr": "Meilleure demande", "hi": "सर्वोत्तम आस्क", "id": "Ask terbaik", "pt": "Melhor venda", "ru": "Лучший запрос", "tr": "En iyi satış", "zh": "最佳卖价"},
    "spread": {"en": "Spread", "ar": "الفارق", "de": "Spanne", "es": "Diferencia", "fa": "اختلاف", "fr": "Écart", "hi": "स्प्रेड", "id": "Selisih", "pt": "Spread", "ru": "Спред", "tr": "Fark", "zh": "价差"},
    "orderBook": {"en": "Order book", "ar": "سجل الأوامر", "de": "Orderbuch", "es": "Libro de órdenes", "fa": "دفتر سفارش‌ها", "fr": "Carnet d'ordres", "hi": "ऑर्डर बुक", "id": "Buku order", "pt": "Livro de ordens", "ru": "Стакан заявок", "tr": "Emir defteri", "zh": "订单簿"},
    "bids": {"en": "Bids", "ar": "أوامر الشراء", "de": "Gebote", "es": "Compras", "fa": "خریدها", "fr": "Achats", "hi": "बिड्स", "id": "Bid", "pt": "Compras", "ru": "Ставки", "tr": "Alışlar", "zh": "买单"},
    "asks": {"en": "Asks", "ar": "أوامر البيع", "de": "Angebote", "es": "Ventas", "fa": "فروش‌ها", "fr": "Ventes", "hi": "आस्क्स", "id": "Ask", "pt": "Vendas", "ru": "Заявки", "tr": "Satışlar", "zh": "卖单"},
    "best": {"en": "best", "ar": "الأفضل", "de": "beste", "es": "mejor", "fa": "بهترین", "fr": "meilleur", "hi": "सर्वोत्तम", "id": "terbaik", "pt": "melhor", "ru": "лучшая", "tr": "en iyi", "zh": "最优"},
    "lastTrade": {"en": "Last", "ar": "آخر صفقة", "de": "Zuletzt", "es": "Último", "fa": "آخرین", "fr": "Dernier", "hi": "अंतिम", "id": "Terakhir", "pt": "Último", "ru": "Последняя", "tr": "Son", "zh": "最新"},
    "recentTrades": {"en": "Recent trades", "ar": "أحدث الصفقات", "de": "Letzte Trades", "es": "Operaciones recientes", "fa": "معاملات اخیر", "fr": "Transactions récentes", "hi": "हाल के ट्रेड", "id": "Transaksi terbaru", "pt": "Negócios recentes", "ru": "Последние сделки", "tr": "Son işlemler", "zh": "最近成交"},
    "tradesLoadError": {"en": "Couldn't load recent trades.", "ar": "تعذر تحميل أحدث الصفقات.", "de": "Letzte Trades konnten nicht geladen werden.", "es": "No se pudieron cargar las operaciones recientes.", "fa": "بارگذاری معاملات اخیر ممکن نشد.", "fr": "Impossible de charger les transactions récentes.", "hi": "हाल के ट्रेड लोड नहीं हो सके।", "id": "Tidak dapat memuat transaksi terbaru.", "pt": "Não foi possível carregar os negócios recentes.", "ru": "Не удалось загрузить последние сделки.", "tr": "Son işlemler yüklenemedi.", "zh": "无法加载最近成交。"},
    "tradesEmpty": {"en": "No trades yet — the market opens when the primary offering sells out.", "ar": "لا توجد صفقات بعد — يفتح السوق عند اكتمال الطرح الأساسي.", "de": "Noch keine Trades — der Markt öffnet, wenn das Primärangebot ausverkauft ist.", "es": "Aún no hay operaciones: el mercado abre cuando se agota la oferta primaria.", "fa": "هنوز معامله‌ای نیست — بازار وقتی عرضه اولیه به پایان برسد باز می‌شود.", "fr": "Pas encore de transactions — le marché ouvre quand l'offre primaire est épuisée.", "hi": "अभी कोई ट्रेड नहीं — प्राथमिक ऑफर बिकने पर बाज़ार खुलेगा।", "id": "Belum ada transaksi — pasar dibuka saat penawaran primer habis.", "pt": "Ainda sem negócios — o mercado abre quando a oferta primária esgotar.", "ru": "Сделок пока нет — рынок откроется, когда распродадут первичное предложение.", "tr": "Henüz işlem yok — birincil arz tükenince pazar açılır.", "zh": "暂无成交——一手发售售罄后市场开放。"},
    "galleryPages": {"en": "Gallery pages", "ar": "صفحات المعرض", "de": "Galerieseiten", "es": "Páginas de galería", "fa": "صفحات گالری", "fr": "Pages de la galerie", "hi": "गैलरी पेज", "id": "Halaman galeri", "pt": "Páginas da galeria", "ru": "Страницы галереи", "tr": "Galeri sayfaları", "zh": "图库页码"},
    "showImage": {"en": "Show image {n}", "ar": "عرض الصورة {n}", "de": "Bild {n} anzeigen", "es": "Mostrar imagen {n}", "fa": "نمایش تصویر {n}", "fr": "Afficher l'image {n}", "hi": "छवि {n} दिखाएँ", "id": "Tampilkan gambar {n}", "pt": "Mostrar imagem {n}", "ru": "Показать изображение {n}", "tr": "{n}. görseli göster", "zh": "显示第 {n} 张图片"},
    "expectedAnnualYield": {"en": "Expected Annual Yield", "ar": "العائد السنوي المتوقع", "de": "Erwartete Jahresrendite", "es": "Rendimiento anual esperado", "fa": "بازده سالانه مورد انتظار", "fr": "Rendement annuel attendu", "hi": "अपेक्षित वार्षिक उपज", "id": "Imbal hasil tahunan yang diharapkan", "pt": "Rendimento anual esperado", "ru": "Ожидаемая годовая доходность", "tr": "Beklenen yıllık getiri", "zh": "预期年化收益"},
    "basedOnLease": {"en": "Based on current lease · {count} {unit} on-time payments", "ar": "استنادًا إلى عقد الإيجار الحالي · {count} {unit} دفعة في الوقت المحدد", "de": "Basierend auf dem aktuellen Mietvertrag · {count} {unit} pünktliche Zahlungen", "es": "Basado en el contrato actual · {count} {unit} pagos puntuales", "fa": "بر اساس اجاره‌نامه فعلی · {count} {unit} پرداخت به‌موقع", "fr": "D'après le bail actuel · {count} {unit} paiements à l'heure", "hi": "वर्तमान लीज़ पर आधारित · {count} {unit} समय पर भुगतान", "id": "Berdasarkan sewa saat ini · {count} {unit} pembayaran tepat waktu", "pt": "Com base no contrato atual · {count} {unit} pagamentos pontuais", "ru": "По текущему договору · {count} {unit} платежей вовремя", "tr": "Mevcut kiraya dayanır · {count} {unit} zamanında ödeme", "zh": "基于当前租约 · {count} {unit} 按时付款"},
    "monthWord": {"en": "month", "ar": "شهر", "de": "Monat", "es": "mes", "fa": "ماه", "fr": "mois", "hi": "महीना", "id": "bulan", "pt": "mês", "ru": "месяц", "tr": "ay", "zh": "个月"},
    "monthsWord": {"en": "months", "ar": "أشهر", "de": "Monate", "es": "meses", "fa": "ماه", "fr": "mois", "hi": "महीने", "id": "bulan", "pt": "meses", "ru": "месяца", "tr": "ay", "zh": "个月"},
    "buySharesAt": {"en": "Buy Shares · {price}", "ar": "شراء الأسهم · {price}", "de": "Anteile kaufen · {price}", "es": "Comprar acciones · {price}", "fa": "خرید سهام · {price}", "fr": "Acheter des actions · {price}", "hi": "शेयर खरीदें · {price}", "id": "Beli saham · {price}", "pt": "Comprar ações · {price}", "ru": "Купить акции · {price}", "tr": "Hisse al · {price}", "zh": "买入股份 · {price}"},
    "buyAt": {"en": "Buy at {price}", "ar": "شراء بسعر {price}", "de": "Kaufen für {price}", "es": "Comprar a {price}", "fa": "خرید با قیمت {price}", "fr": "Acheter à {price}", "hi": "{price} पर खरीदें", "id": "Beli di {price}", "pt": "Comprar a {price}", "ru": "Купить за {price}", "tr": "{price} fiyatına al", "zh": "以 {price} 买入"},
    "offeringSoldOut": {"en": "Primary offering sold out", "ar": "نفدت الطروحة الأساسية", "de": "Primärangebot ausverkauft", "es": "Oferta primaria agotada", "fa": "عرضه اولیه به پایان رسید", "fr": "Offre primaire épuisée", "hi": "प्राथमिक ऑफर बिक चुका", "id": "Penawaran primer habis", "pt": "Oferta primária esgotada", "ru": "Первичное предложение распродано", "tr": "Birincil arz tükendi", "zh": "一手发售已售罄"},
    "stickyBuyShares": {"en": "Buy Shares · {price}", "ar": "شراء الأسهم · {price}", "de": "Anteile kaufen · {price}", "es": "Comprar acciones · {price}", "fa": "خرید سهام · {price}", "fr": "Acheter des actions · {price}", "hi": "शेयर खरीदें · {price}", "id": "Beli saham · {price}", "pt": "Comprar ações · {price}", "ru": "Купить акции · {price}", "tr": "Hisse al · {price}", "zh": "买入股份 · {price}"},
    "stickyBuy": {"en": "Buy · {price}", "ar": "شراء · {price}", "de": "Kaufen · {price}", "es": "Comprar · {price}", "fa": "خرید · {price}", "fr": "Acheter · {price}", "hi": "खरीदें · {price}", "id": "Beli · {price}", "pt": "Comprar · {price}", "ru": "Купить · {price}", "tr": "Al · {price}", "zh": "买入 · {price}"},
    "sell": {"en": "Sell", "ar": "بيع", "de": "Verkaufen", "es": "Vender", "fa": "فروش", "fr": "Vendre", "hi": "बेचें", "id": "Jual", "pt": "Vender", "ru": "Продать", "tr": "Sat", "zh": "卖出"},
    "pricePerShareMetric": {"en": "Price per share", "ar": "سعر السهم", "de": "Preis pro Anteil", "es": "Precio por acción", "fa": "قیمت هر سهم", "fr": "Prix par action", "hi": "प्रति शेयर कीमत", "id": "Harga per saham", "pt": "Preço por ação", "ru": "Цена за акцию", "tr": "Hisse başına fiyat", "zh": "每股价格"},
    "monthlyYieldPerShare": {"en": "Monthly yield / share", "ar": "العائد الشهري / سهم", "de": "Monatsertrag / Anteil", "es": "Rendimiento mensual / acción", "fa": "بازده ماهانه / سهم", "fr": "Rendement mensuel / action", "hi": "मासिक उपज / शेयर", "id": "Imbal hasil bulanan / saham", "pt": "Rendimento mensal / ação", "ru": "Доходность в месяц / акция", "tr": "Aylık getiri / hisse", "zh": "月收益 / 股"},
    "totalPropertyValue": {"en": "Total property value", "ar": "القيمة الإجمالية للعقار", "de": "Gesamtwert der Immobilie", "es": "Valor total de la propiedad", "fa": "ارزش کل ملک", "fr": "Valeur totale du bien", "hi": "कुल संपत्ति मूल्य", "id": "Nilai total properti", "pt": "Valor total do imóvel", "ru": "Полная стоимость объекта", "tr": "Toplam mülk değeri", "zh": "物业总价值"},
    "about": {"en": "About", "ar": "نبذة", "de": "Über", "es": "Acerca de", "fa": "درباره", "fr": "À propos", "hi": "परिचय", "id": "Tentang", "pt": "Sobre", "ru": "О объекте", "tr": "Hakkında", "zh": "关于"},
    "moreDetails": {"en": "More details", "ar": "مزيد من التفاصيل", "de": "Weitere Details", "es": "Más detalles", "fa": "جزئیات بیشتر", "fr": "Plus de détails", "hi": "और विवरण", "id": "Detail selengkapnya", "pt": "Mais detalhes", "ru": "Подробнее", "tr": "Daha fazla detay", "zh": "更多详情"},
    "sizeLabel": {"en": "Size", "ar": "المساحة", "de": "Größe", "es": "Tamaño", "fa": "اندازه", "fr": "Taille", "hi": "आकार", "id": "Ukuran", "pt": "Tamanho", "ru": "Площадь", "tr": "Alan", "zh": "面积"},
    "yearBuilt": {"en": "Year built", "ar": "سنة البناء", "de": "Baujahr", "es": "Año de construcción", "fa": "سال ساخت", "fr": "Année de construction", "hi": "निर्माण वर्ष", "id": "Tahun dibangun", "pt": "Ano de construção", "ru": "Год постройки", "tr": "İnşaat yılı", "zh": "建造年份"},
    "typeLabel": {"en": "Type", "ar": "النوع", "de": "Typ", "es": "Tipo", "fa": "نوع", "fr": "Type", "hi": "प्रकार", "id": "Tipe", "pt": "Tipo", "ru": "Тип", "tr": "Tür", "zh": "类型"},
    "rentalStatusLabel": {"en": "Rental status", "ar": "حالة التأجير", "de": "Mietstatus", "es": "Estado de alquiler", "fa": "وضعیت اجاره", "fr": "Statut locatif", "hi": "किराया स्थिति", "id": "Status sewa", "pt": "Status de aluguel", "ru": "Статус аренды", "tr": "Kira durumu", "zh": "租赁状态"},
    "leaseUntil": {"en": "Lease until", "ar": "الإيجار حتى", "de": "Miete bis", "es": "Alquiler hasta", "fa": "اجاره تا", "fr": "Bail jusqu'au", "hi": "लीज़ तक", "id": "Sewa hingga", "pt": "Arrendamento até", "ru": "Аренда до", "tr": "Kira bitişi", "zh": "租约至"},
    "trustTitle": {"en": "Why invest with confidence", "ar": "لماذا تستثمر بثقة", "de": "Warum Sie vertrauensvoll investieren", "es": "Por qué invertir con confianza", "fa": "چرا با اطمینان سرمایه‌گذاری کنید", "fr": "Pourquoi investir en confiance", "hi": "विश्वास से क्यों निवेश करें", "id": "Mengapa berinvest dengan percaya diri", "pt": "Por que investir com confiança", "ru": "Почему стоит инвестировать", "tr": "Neden güvenle yatırım yapmalısınız", "zh": "为何值得放心投资"},
    "trustSimulatedNote": {"en": "Payment history reflects simulated demo records.", "ar": "سجل الدفعات يعكس سجلات تجريبية محاكاة.", "de": "Der Zahlungsverlauf basiert auf simulierten Demodaten.", "es": "El historial de pagos refleja registros simulados de demostración.", "fa": "سابقه پرداخت‌ها بازتاب داده‌های نمایشی شبیه‌سازی‌شده است.", "fr": "L'historique de paiement reflète des données de démonstration simulées.", "hi": "भुगतान इतिहास सिम्युलेटेड डेमो रिकॉर्ड दिखाता है।", "id": "Riwayat pembayaran mencerminkan catatan demo simulasi.", "pt": "O histórico de pagamentos reflete registros simulados de demonstração.", "ru": "История платежей отражает смоделированные демо-данные.", "tr": "Ödeme geçmişi simüle edilmiş demo kayıtları yansıtır.", "zh": "付款历史为模拟演示数据。"},
    "similarProperties": {"en": "Similar properties", "ar": "عقارات مشابهة", "de": "Ähnliche Immobilien", "es": "Propiedades similares", "fa": "املاک مشابه", "fr": "Biens similaires", "hi": "समान संपत्तियाँ", "id": "Properti serupa", "pt": "Imóveis similares", "ru": "Похожие объекты", "tr": "Benzer mülkler", "zh": "类似物业"},
    "simulatedPriceNote": {"en": "Simulated price history for illustration — not a promise of future returns.", "ar": "سجل سعر محاكاة للتوضيح — ليس وعدًا بعوائد مستقبلية.", "de": "Simulierter Preisverlauf zur Veranschaulichung — kein Versprechen künftiger Renditen.", "es": "Historial de precios simulado a modo ilustrativo: no es una promesa de rendimientos futuros.", "fa": "سابقه قیمت شبیه‌سازی‌شده برای توضیح — وعده بازده آینده نیست.", "fr": "Historique de prix simulé à titre d'illustration — pas une promesse de rendements futurs.", "hi": "उदाहरण के लिए सिम्युलेटेड मूल्य इतिहास — भविष्य के रिटर्न का वादा नहीं।", "id": "Riwayat harga simulasi untuk ilustrasi — bukan janji imbal hasil masa depan.", "pt": "Histórico de preços simulado para ilustração — não é promessa de retornos futuros.", "ru": "Смоделированная история цен для наглядности — не обещание будущей доходности.", "tr": "Görsel amaçlı simüle fiyat geçmişi — gelecek getirilerin garantisi değildir.", "zh": "模拟价格历史仅供示意——不构成对未来收益的承诺。"},
    "bannerLockCta": {"en": "Lock shares to start earning", "ar": "اقفل الأسهم لتبدأ الكسب", "de": "Anteile sperren und verdienen", "es": "Bloquea acciones para empezar a ganar", "fa": "برای شروع کسب درآمد، سهام را قفل کنید", "fr": "Verrouillez des actions pour commencer à gagner", "hi": "कमाई शुरू करने के लिए शेयर लॉक करें", "id": "Kunci saham untuk mulai menghasilkan", "pt": "Bloqueie ações para começar a ganhar", "ru": "Заблокируйте акции, чтобы начать зарабатывать", "tr": "Kazanmaya başlamak için hisseleri kilitleyin", "zh": "锁定股份开始收益"},
    "youOwn": {"en": "You own {count} {unit} · {locked} locked", "ar": "تملك {count} {unit} · {locked} مقفل", "de": "Du besitzt {count} {unit} · {locked} gesperrt", "es": "Tienes {count} {unit} · {locked} bloqueadas", "fa": "شما {count} {unit} دارید · {locked} قفل‌شده", "fr": "Vous possédez {count} {unit} · {locked} verrouillées", "hi": "आपके पास {count} {unit} हैं · {locked} लॉक", "id": "Anda memiliki {count} {unit} · {locked} terkunci", "pt": "Você possui {count} {unit} · {locked} bloqueadas", "ru": "У вас {count} {unit} · {locked} заблокировано", "tr": "{count} {unit} sahibisiniz · {locked} kilitli", "zh": "您持有 {count} {unit} · {locked} 股已锁定"},
    "earningNow": {"en": "Earning", "ar": "يكسب", "de": "Erwirtschaftet", "es": "Generando", "fa": "در حال کسب درآمد", "fr": "Rémunéré", "hi": "कमा रहा है", "id": "Menghasilkan", "pt": "Rendendo", "ru": "Приносит доход", "tr": "Kazanıyor", "zh": "收益中"},
    "notEarningYet": {"en": "Not earning yet", "ar": "لا يكسب بعد", "de": "Noch kein Ertrag", "es": "Aún no genera", "fa": "هنوز درآمد ندارد", "fr": "Pas encore rémunéré", "hi": "अभी कमाई नहीं", "id": "Belum menghasilkan", "pt": "Ainda não rende", "ru": "Пока не приносит доход", "tr": "Henüz kazanmıyor", "zh": "尚未产生收益"},
    "bannerLockNote": {"en": "Shares only earn yield while locked. Locking is free — unlock takes 2–3 days if you change your mind.", "ar": "الأسهم تكسب عائدًا فقط أثناء الإقفال. الإقفال مجاني — يستغرق الفتح 2–3 أيام إذا غيّرت رأيك.", "de": "Anteile erwirtschaften nur Ertrag, während sie gesperrt sind. Sperren ist kostenlos — Entsperren dauert 2–3 Tage, falls Sie es sich anders überlegen.", "es": "Las acciones solo generan rendimiento bloqueadas. Bloquear es gratis: desbloquear tarda 2–3 días si cambia de opinión.", "fa": "سهام فقط وقتی قفل هستند بازده می‌دهند. قفل کردن رایگان است — اگر نظرتان عوض شود، باز کردن ۲ تا ۳ روز طول می‌کشد.", "fr": "Les actions ne rapportent que lorsqu'elles sont verrouillées. Le verrouillage est gratuit — le déverrouillage prend 2 à 3 jours si vous changez d'avis.", "hi": "शेयर केवल लॉक होने पर उपज देते हैं। लॉक करना मुफ्त है — मन बदलने पर अनलॉक में 2–3 दिन लगते हैं।", "id": "Saham hanya menghasilkan imbal hasil saat terkunci. Mengunci gratis — membuka memakan 2–3 hari jika Anda berubah pikiran.", "pt": "As ações só rendem enquanto bloqueadas. Bloquear é grátis — desbloquear leva 2–3 dias se mudar de ideia.", "ru": "Акции приносят доход, только пока заблокированы. Блокировка бесплатна — разблокировка занимает 2–3 дня, если передумаете.", "tr": "Hisseler yalnızca kilitliyken getiri sağlar. Kilitlemek ücretsizdir — fikrinizi değiştirirseniz açmak 2–3 gün sürer.", "zh": "股份仅在锁定期间产生收益。锁定免费——如改变主意，解锁需 2–3 天。"},
}


def main():
    for loc in LOCALES:
        path = f"messages/{loc}.json"
        with io.open(path, "r", encoding="utf-8") as f:
            data = json.load(f, object_pairs_hook=collections.OrderedDict)
        prop = data.setdefault("property", collections.OrderedDict())
        added = 0
        for key, per_locale in K.items():
            if key in prop:
                continue
            prop[key] = per_locale[loc]
            added += 1
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"{loc}: +{added}")


if __name__ == "__main__":
    main()
